# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(445, 538)
        icon = QtGui.QIcon.fromTheme("user-away")
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_Register = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_Register.setGeometry(QtCore.QRect(10, 20, 421, 331))
        self.groupBox_Register.setStyleSheet("color:  white;\n"
"background-color: rgb(59, 59, 59);")
        self.groupBox_Register.setObjectName("groupBox_Register")
        self.username_Input_Registration = QtWidgets.QLineEdit(parent=self.groupBox_Register)
        self.username_Input_Registration.setGeometry(QtCore.QRect(20, 70, 321, 25))
        self.username_Input_Registration.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.username_Input_Registration.setObjectName("username_Input_Registration")
        self.password_Input_Registration = QtWidgets.QLineEdit(parent=self.groupBox_Register)
        self.password_Input_Registration.setGeometry(QtCore.QRect(20, 120, 321, 25))
        self.password_Input_Registration.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.password_Input_Registration.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.password_Input_Registration.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_Input_Registration.setObjectName("password_Input_Registration")
        self.label_usr_reg = QtWidgets.QLabel(parent=self.groupBox_Register)
        self.label_usr_reg.setGeometry(QtCore.QRect(20, 50, 71, 17))
        self.label_usr_reg.setStyleSheet("color: rgb(255, 0, 127);")
        self.label_usr_reg.setObjectName("label_usr_reg")
        self.label_pass_reg = QtWidgets.QLabel(parent=self.groupBox_Register)
        self.label_pass_reg.setGeometry(QtCore.QRect(20, 100, 91, 17))
        self.label_pass_reg.setStyleSheet("color: rgb(255, 0, 127);")
        self.label_pass_reg.setObjectName("label_pass_reg")
        self.checkBox_accept = QtWidgets.QCheckBox(parent=self.groupBox_Register)
        self.checkBox_accept.setGeometry(QtCore.QRect(20, 210, 111, 23))
        self.checkBox_accept.setStyleSheet("color: rgb(255, 0, 127);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"    border: 3px solid #5A5A5A;\n"
"    background: none;\n"
"\n"
"")
        self.checkBox_accept.setObjectName("checkBox_accept")
        self.register_Button = QtWidgets.QPushButton(parent=self.groupBox_Register)
        self.register_Button.setGeometry(QtCore.QRect(260, 210, 80, 25))
        self.register_Button.setStyleSheet("color: rgb(0, 255, 162);\n"
"background-color: rgb(27, 27, 27);")
        self.register_Button.setObjectName("register_Button")
        self.label_email = QtWidgets.QLabel(parent=self.groupBox_Register)
        self.label_email.setGeometry(QtCore.QRect(20, 150, 91, 17))
        self.label_email.setStyleSheet("color: rgb(255, 0, 127);")
        self.label_email.setObjectName("label_email")
        self.label = QtWidgets.QLabel(parent=self.groupBox_Register)
        self.label.setGeometry(QtCore.QRect(20, 250, 91, 17))
        self.label.setObjectName("label")
        self.STATE = QtWidgets.QLabel(parent=self.groupBox_Register)
        self.STATE.setGeometry(QtCore.QRect(120, 250, 91, 17))
        self.STATE.setStyleSheet("color: rgb(255, 0, 4);")
        self.STATE.setObjectName("STATE")
        self.label_version = QtWidgets.QLabel(parent=self.groupBox_Register)
        self.label_version.setGeometry(QtCore.QRect(20, 270, 81, 17))
        self.label_version.setObjectName("label_version")
        self.VERSION = QtWidgets.QLabel(parent=self.groupBox_Register)
        self.VERSION.setGeometry(QtCore.QRect(120, 270, 91, 17))
        self.VERSION.setStyleSheet("color: rgb(4, 255, 0);")
        self.VERSION.setObjectName("VERSION")
        self.email_Input_Registration = QtWidgets.QLineEdit(parent=self.groupBox_Register)
        self.email_Input_Registration.setGeometry(QtCore.QRect(20, 170, 321, 25))
        self.email_Input_Registration.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.email_Input_Registration.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhEmailCharactersOnly)
        self.email_Input_Registration.setObjectName("email_Input_Registration")
        self.hyperlink_login = QtWidgets.QLabel(parent=self.groupBox_Register)
        self.hyperlink_login.setGeometry(QtCore.QRect(90, 300, 201, 17))
        self.hyperlink_login.setStyleSheet("color: rgb(0, 255, 162);\n"
"background-color: rgb(27, 27, 27);")
        self.hyperlink_login.setObjectName("hyperlink_login")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(0, 490, 441, 23))
        self.progressBar.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.consoleLog = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.consoleLog.setGeometry(QtCore.QRect(10, 390, 421, 91))
        self.consoleLog.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(0, 255, 162);")
        self.consoleLog.setObjectName("consoleLog")
        self.label_log = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_log.setGeometry(QtCore.QRect(20, 370, 61, 17))
        self.label_log.setObjectName("label_log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "blackzspace.de || Register"))
        self.groupBox_Register.setTitle(_translate("MainWindow", "Register"))
        self.label_usr_reg.setText(_translate("MainWindow", "Username:"))
        self.label_pass_reg.setText(_translate("MainWindow", "Password:"))
        self.checkBox_accept.setText(_translate("MainWindow", "Accept Rules "))
        self.register_Button.setText(_translate("MainWindow", "Register"))
        self.label_email.setText(_translate("MainWindow", "E-Mail:"))
        self.label.setText(_translate("MainWindow", "Server Status:"))
        self.STATE.setText(_translate("MainWindow", "n/A"))
        self.label_version.setText(_translate("MainWindow", "Version:"))
        self.VERSION.setText(_translate("MainWindow", "VERSION"))
        self.hyperlink_login.setText(_translate("MainWindow", "Already have an Account ?! Login !!"))
        self.label_log.setText(_translate("MainWindow", "Log:"))
