# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 577)
        icon = QtGui.QIcon.fromTheme("user-available")
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_Login = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_Login.setGeometry(QtCore.QRect(10, 20, 401, 361))
        self.groupBox_Login.setStyleSheet("color:  white;\n"
"background-color: rgb(59, 59, 59);\n"
"")
        self.groupBox_Login.setObjectName("groupBox_Login")
        self.username_Input = QtWidgets.QLineEdit(parent=self.groupBox_Login)
        self.username_Input.setGeometry(QtCore.QRect(20, 70, 321, 25))
        self.username_Input.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.username_Input.setObjectName("username_Input")
        self.password_Input = QtWidgets.QLineEdit(parent=self.groupBox_Login)
        self.password_Input.setGeometry(QtCore.QRect(20, 120, 321, 25))
        self.password_Input.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.password_Input.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.password_Input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_Input.setObjectName("password_Input")
        self.label_usr = QtWidgets.QLabel(parent=self.groupBox_Login)
        self.label_usr.setGeometry(QtCore.QRect(20, 50, 71, 17))
        self.label_usr.setStyleSheet("color: rgb(255, 0, 127);")
        self.label_usr.setObjectName("label_usr")
        self.label_pass = QtWidgets.QLabel(parent=self.groupBox_Login)
        self.label_pass.setGeometry(QtCore.QRect(20, 100, 91, 17))
        self.label_pass.setStyleSheet("color: rgb(255, 0, 127);")
        self.label_pass.setObjectName("label_pass")
        self.checkBox_remember = QtWidgets.QCheckBox(parent=self.groupBox_Login)
        self.checkBox_remember.setGeometry(QtCore.QRect(20, 160, 123, 23))
        self.checkBox_remember.setStyleSheet("color: rgb(255, 0, 127);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"    border: 3px solid #5A5A5A;\n"
"    background: none;\n"
"\n"
"")
        self.checkBox_remember.setObjectName("checkBox_remember")
        self.login_Button = QtWidgets.QPushButton(parent=self.groupBox_Login)
        self.login_Button.setGeometry(QtCore.QRect(260, 150, 80, 25))
        self.login_Button.setStyleSheet("color: rgb(0, 255, 162);background-color: rgb(27, 27, 27);")
        self.login_Button.setObjectName("login_Button")
        self.hyperlink_register = QtWidgets.QLabel(parent=self.groupBox_Login)
        self.hyperlink_register.setGeometry(QtCore.QRect(20, 190, 201, 17))
        self.hyperlink_register.setStyleSheet("background-color: rgb(27, 27, 27);\n"
"color: rgb(0, 255, 162);")
        self.hyperlink_register.setObjectName("hyperlink_register")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(0, 520, 431, 23))
        self.progressBar.setStyleSheet("background-color: rgb(27, 27, 27);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.consoleLog = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.consoleLog.setGeometry(QtCore.QRect(10, 420, 401, 91))
        self.consoleLog.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(0, 255, 162);")
        self.consoleLog.setObjectName("consoleLog")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 290, 91, 17))
        self.label.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.label.setObjectName("label")
        self.label_version = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_version.setGeometry(QtCore.QRect(30, 320, 81, 17))
        self.label_version.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.label_version.setObjectName("label_version")
        self.STATE = QtWidgets.QLabel(parent=self.centralwidget)
        self.STATE.setGeometry(QtCore.QRect(120, 290, 91, 17))
        self.STATE.setStyleSheet("background-color: rgb(59, 59, 59);color: rgb(255, 0, 4);")
        self.STATE.setObjectName("STATE")
        self.VERSION = QtWidgets.QLabel(parent=self.centralwidget)
        self.VERSION.setGeometry(QtCore.QRect(110, 320, 91, 17))
        self.VERSION.setStyleSheet("background-color: rgb(59, 59, 59);color: rgb(4, 255, 0);")
        self.VERSION.setObjectName("VERSION")
        self.label_log = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_log.setGeometry(QtCore.QRect(10, 400, 61, 20))
        self.label_log.setObjectName("label_log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "blackzspace.de || Login "))
        self.groupBox_Login.setTitle(_translate("MainWindow", "Login"))
        self.label_usr.setText(_translate("MainWindow", "Username:"))
        self.label_pass.setText(_translate("MainWindow", "Password:"))
        self.checkBox_remember.setText(_translate("MainWindow", "Remember"))
        self.login_Button.setText(_translate("MainWindow", "Login"))
        self.hyperlink_register.setText(_translate("MainWindow", "Dont have an Account? Register!"))
        self.label.setText(_translate("MainWindow", "Server Status:"))
        self.label_version.setText(_translate("MainWindow", "Version:"))
        self.STATE.setText(_translate("MainWindow", "n/A"))
        self.VERSION.setText(_translate("MainWindow", "VERSION"))
        self.label_log.setText(_translate("MainWindow", "Log:"))
